### PR TITLE
Add coffeescript bindings

### PR DESCRIPTION
**Pull request by jgarth**
Hi @seifsallam,

Thanks for publishing your snippets. I took the liberty of duplicating all snippets in [CoffeeScript](http://coffeescript.org). I've also adjusted the Readme, Changelog and `package.json`. Would you be willing to pull them into your package? Let me know if any additional changes are necessary.

### CODE REVIEW

**Comment by jgarth** [comment]
Whoa, I could swear I saw no pull requests for this and now I can see there are two already... my bad! Feel free to close & ignore in favor of #2 / #3 / #4

**Comment by seifsallam** [comment]
This looks more ready. Can you just update the `.property` and `.observer` to use new syntax `Ember.computed` and `Ember.observer` https://github.com/emberjs/guides/pull/110

**Comment by seifsallam** [comment]
@jgarth This looks more ready. Can you just update the `.property` and `.observer` to use new syntax `Ember.computed` and `Ember.observer` https://github.com/emberjs/guides/pull/110

**Comment by jgarth** [comment]
Thanks for the hint, the new syntax seems much nicer in conjunction with CoffeeScript.

**Comment by seifsallam** [comment]
@jgarth I've updated the package. Thanks for your PR :+1:

**Comment by jgarth** [comment]
Cheers! :+1:

**Pull request merged**
