### PR TITLE
Add snippets for Ember Enumerables

### PR DESCRIPTION
**Pull request by taylon**
Enumerables are quite common currently so I added all the ones supported both in js and coffee =D

### CODE REVIEW

**Comment by seifsallam** [comment]
Thats awesome (sorry for the late reply). Can you just remove prepending variable, match prefix with function name (ex: use `forEach` instead `fore`), and remove functions that existing in JS autocomplete like `.map`. Thanks :)

**Comment by seifsallam** [comment]
Also can you update the README

**Comment by taylon** [comment]
Absolutely I'll do it until the end of the week.

**Comment by taylon** [comment]
@seifsallam a couple of questions:

- Variable assignment: Do you really think we should remove it? Those methods are most of the time used with variable assignment (at least as far as I know). In addition to that, I made all of them optional, so if you just hit backspace they will be removed and you can move to the next breakpoint and continue filling the snippet.

- .filter and .map: I checked the [language-javascript](https://github.com/atom/language-javascript/blob/master/snippets/language-javascript.cson) and they are not there, you mean another package that includes it?

I already changed the functions names and updated the README, just wanted to discuss these two before the pull request.

**Comment by seifsallam** [comment]
@taylon 
1. Yes, and yes, but I believe it should be up to the user to assign it to a variable themselves. Some prefer defining variables at the top, some would want to chain methods. Problem with backspace that it would break users typing flow, so it's the better to keep it simple.
2. Yes, I'm actually using https://atom.io/packages/turbo-javascript

**Comment by taylon** [comment]
@seifsallam 

Cool, so there we go, let me know if there is any other change you would like to see.

**Comment by seifsallam** [comment]
@taylon Awesome. Thanks for the PR :+1: :)

**Pull request merged**
